version: "3.7"
services:
  api_service:
    build: .
    container_name: school_service
    #restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
  postgres_db:
    image: "postgres:11.4"
    container_name: schooldb
    #restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: java_to_dev_app_db
      POSTGRES_PASSWORD: nE5kMc7JCGNqwDQM