DELETE FROM public.course;
INSERT INTO public.course (course_name) VALUES('course1');
INSERT INTO public.course (course_name) VALUES('course2');
INSERT INTO public.course (course_name) VALUES('course3');
INSERT INTO public.course (course_name) VALUES('course4');
INSERT INTO public.course (course_name) VALUES('course5');
INSERT INTO public.course (course_name) VALUES('course6');
INSERT INTO public.course (course_name) VALUES('course7');

DELETE FROM public.student;
INSERT INTO public.student (student_name) VALUES('student1');
INSERT INTO public.student (student_name) VALUES('student2');
INSERT INTO public.student (student_name) VALUES('student3');
INSERT INTO public.student (student_name) VALUES('student4');
INSERT INTO public.student (student_name) VALUES('student5');
INSERT INTO public.student (student_name) VALUES('student6');
INSERT INTO public.student (student_name) VALUES('student7');
INSERT INTO public.student (student_name) VALUES('student8');

DELETE FROM public.enrollment;
INSERT INTO public.enrollment (student_id, course_id) VALUES(1, 1);
INSERT INTO public.enrollment (student_id, course_id) VALUES(1, 2);
INSERT INTO public.enrollment (student_id, course_id) VALUES(1, 3);
INSERT INTO public.enrollment (student_id, course_id) VALUES(1, 4);
INSERT INTO public.enrollment (student_id, course_id) VALUES(1, 5);
INSERT INTO public.enrollment (student_id, course_id) VALUES(2, 2);
INSERT INTO public.enrollment (student_id, course_id) VALUES(3, 3);
INSERT INTO public.enrollment (student_id, course_id) VALUES(4, 1);
INSERT INTO public.enrollment (student_id, course_id) VALUES(4, 3);
INSERT INTO public.enrollment (student_id, course_id) VALUES(5, 2);
INSERT INTO public.enrollment (student_id, course_id) VALUES(6, 1);
